#version: '3.8'
#
#services:
#  nginx:
#    image: nginx:alpine
#    volumes:
#      - ./:/var/www/html/:delegated
#      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./.docker/nginx/sites/:/etc/nginx/sites-available
#      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
#    depends_on:
#      - php
#    networks:
#      demo-net:
#        aliases:
#          - demo.local
#    ports:
#      - "8000:80"
#  php:
##    build: './docker/php'
#    image: thecodingmachine/php:8.1.13-v4-fpm
#    volumes:
#      - ./:/var/www/html/:delegated
#    environment:
#      PHP_INI_MAX_EXECUTION_TIME: "300"
#      PHP_EXTENSION_INTL: 1
#      PHP_EXTENSION_XDEBUG: 1
#      PHP_INI_XDEBUG__MODE: "debug,develop"
#      PHP_INI_XDEBUG__CLIENT_PORT: 10000
#      PHP_INI_XDEBUG__IDEKEY: PHPSTORM
#      PHP_INI_XDEBUG__START_WITH_REQUEST: yes
#      PHP_IDE_CONFIG: "serverName=demo.local"
#      PHP_EXTENSION_PGSQL: 1
#      PHP_EXTENSION_PDO_PGSQL: 1
#      PHP_EXTENSION_MYSQLI: 0
#      PHP_EXTENSION_AMQP: 1
#      PHP_EXTENSION_GD: 1
#    #      STARTUP_COMMAND_1: composer install
#    #      STARTUP_COMMAND_2: php bin/console do:m:m --no-interaction
#    #      STARTUP_COMMAND_3: php bin/console do:f:l --group=default --no-interaction
#    networks:
#      - demo-net
#      -
version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html/:delegated
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./.docker/nginx/sites/:/etc/nginx/sites-available
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php
  php:
    image: thecodingmachine/php:8.1.13-v4-fpm
    volumes:
      - ./:/var/www/html/:delegated
    environment:
      PHP_INI_MAX_EXECUTION_TIME: "300"
      PHP_EXTENSION_INTL: 1
      PHP_EXTENSION_XDEBUG: 1
      PHP_INI_XDEBUG__MODE: "debug,develop"
      PHP_INI_XDEBUG__CLIENT_PORT: 10000
      PHP_INI_XDEBUG__IDEKEY: PHPSTORM
      PHP_INI_XDEBUG__START_WITH_REQUEST: yes
      PHP_IDE_CONFIG: "serverName=demo.local"
      PHP_EXTENSION_PGSQL: 1
      PHP_EXTENSION_PDO_PGSQL: 1
      PHP_EXTENSION_MYSQLI: 0
      PHP_EXTENSION_AMQP: 1
      PHP_EXTENSION_GD: 1